### ISSUE TITLE
Milestones 4.0

### ISSUE THREAD

**Issue by cschuchardt88** [neo-project/neo-express#411]
Can we get some milestones started.

**I am Currently Working on**
- [ ] WebSocket server for `neo-express` node _(command and control node) or [neo-modules#847](https://github.com/neo-project/neo-modules/pull/847)_
- [ ] New vscode extension & UI with websockets
  - [ ] new engine _(vuejs)_
  - [ ] new layouts design _(figma)_
  - [ ] bug fixes _(invoke-files, etc)_
  - [ ] use new websocket interface
  - [ ] More as it comes.

**Areas that need help**
- Unit Testing Framework
- Adding functionally for websockets to control/get node information
- Documentation
- More to come....

Post current work-ins in this issue

@Liaojinghui @Ashuaidehao @chenzhitong @steven1227 

Also any input or help is much appreciate it. 😸

**Comment by steven1227** [comment]
Just split the tasks and let us work together. I know @Celia18305 is working on docs.  @Ashuaidehao and @chenzhitong has other PR open for review but can help to fix more issues later.

**Comment by cschuchardt88** [comment]
No milestone for now.
